[package]
name = "crypto-pure"
version = "0.0.9"
authors = ["Taylor Barrella <tbarrella@gmail.com>"]
edition = "2021"

[dependencies]
byteorder = { version = ">=1.4.3", default-features = false }

[features]
default = ["std"]
std = []
